### PR TITLE
ActiveAdmin 1.0.0-pre Action Buttons compatibility fix

### LINKED ISSUE #22: Wrong styles for "Add entity" and "Remove entity" action buttons.
Here is a screenshot of active_skin view from README:

https://raw.githubusercontent.com/ilu2112/active_skin/master/doc/active-skin-users.png

As You can see - there is a button with "Stwórz obiekt użytkownik" string.

Here is how I see it after adding active_skin to rails 4.1.6 project:

active_skin_bug

"New Admin User" button has different style.

EDIT: this issue seems to be fixed with commit:

 https://github.com/Evan-M/active_skin/commit/aa7b16a3c541bfbbf4b066fa9aca03930e5fd537

### PR DESCRIPTION
**Pull request by RaVbaker**
To react on recent changes in HTML/CSS structure in [ActiveAdmin 1.0.0-pre](https://github.com/activeadmin/activeadmin/commit/64412b82de02f764eac5f90df4ca22e956618f57) version.

Inspired by https://github.com/Evan-M/active_skin/commit/aa7b16a3c541bfbbf4b066fa9aca03930e5fd537

Fixes #22 

Hope it will be merged soon!

### CODE REVIEW

**Comment by raldred** [comment]
Please can we get this merged

**Comment by robomc** [comment]
This would be great to have merged in.

**Comment by yoonwaiyan** [comment]
+1

**Comment by wojtek-krysiak** [comment]
Done - sorry guys it took so long :/

**Comment by raldred** [comment]
Thanks @wojtek-krysiak :+1: :+1:

**Pull request merged**
