### PR TITLE
Add colors variables

### PR DESCRIPTION
**Pull request by viniciusalmeida**
Add variables to text color in skin and panel headers

### CODE REVIEW

**Comment by matheusazzi** [comment]
:+1:

**Comment by giulianovarriale** [comment]
:+1:

**Comment by paulodiovani** [comment]
:+1:

**Comment by viniciusalmeida** [comment]
The cause:

captura_de_tela_2015-03-27_17_59_37

**Comment by matheusazzi** [comment]
@wojtek-krysiak

**Comment by wojtek-krysiak** [comment]
Thanks - I've updated it rubygems as well.

**Pull request merged**
